name: mi primer pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ${{ secrets.DOCKER_USERNAME }}
  # Extraemos solo el nombre del repositorio sin el propietario
  REPONAME: ${{ github.event.repository.name }}
  VERSION: "v1"

jobs:

  init_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '21'
    - name: run tests
      run: | 
        echo "corriendo test"
        npm install
        npm test

  build:
    runs-on: ubuntu-latest
    needs: [init_test]
    steps:
    - uses: actions/checkout@v4
    - name: Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: 🔑 Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: .
        # platforms: linux/amd64,linux/arm64
        tags: ${{ env.REGISTRY }}/${{ env.REPONAME }}:${{ env.VERSION }}
        # También podemos agregar la etiqueta latest
        # tags: |
        #   ${{ env.REGISTRY }}/${{ env.REPONAME }}:${{ env.VERSION }}
        #   ${{ env.REGISTRY }}/${{ env.REPONAME }}:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v4

  notify:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}