name: Mi primer pipeline ED

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Listar directorio
      run: ls -la

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Listar directorio
      run: |
        echo "Ejecutando pruebas"
        ls -la
        echo "Pruebas completadas"

  build:
    runs-on: ubuntu-latest
    needs: [init, test]
    steps:
    - uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v4

  notify:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - uses: actions/checkout@v4