name: Mi primer pipeline ED

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '21'
    - name: Instalar dependencias
      run: |
        echo "Instalando dependencias"
        npm install
        echo "Dependencias instaladas"

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '21'
    - name: Run tests
      run: |
        echo "Corriendo tests"
        npm install
        npm test
        echo "Tests completados"

  build:
    runs-on: ubuntu-latest
    needs: [init, test]
    steps:
    - uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v4

  notify:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - uses: actions/checkout@v4